language: go

go:
  # - "1.x"
  - "1.11.x"
  # - "master"

before_install:
  - curl -L https://git.io/vp6lP | sed 's/install -d "${BINDIR}"//' | sh -s -- -b "${GOPATH}/bin"

script:
  - "make validate"
  - "make test"
